UNAUTHORIZED = "UNAUTHORIZED"
PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
MALFORMED_SCAN = "MALFORMED_SCAN"
NO_FACE = "NO_FACE"
MULTI_FACE = "MULTI_FACE"
USER_NOT_FOUND = "USER_NOT_FOUND"

MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"

LIVENESS_FAIL = "LIVENESS_FAIL"

CHALLENGE_FAIL = "CHALLENGE_FAIL"

LOW_QUALITY = "LOW_QUALITY"

BUSY = "BUSY"

ACTIVE = frozenset(
    {
        UNAUTHORIZED,
        PAYLOAD_TOO_LARGE,
        MALFORMED_SCAN,
        NO_FACE,
        MULTI_FACE,
        USER_NOT_FOUND,
        MODEL_UNAVAILABLE,
        LIVENESS_FAIL,
        CHALLENGE_FAIL,
        LOW_QUALITY,
        BUSY,
    }
)
RESERVED: frozenset = frozenset()
ENGINE_CODES = ACTIVE | RESERVED

HTTP_STATUS = {
    UNAUTHORIZED: 401,
    PAYLOAD_TOO_LARGE: 413,
    MALFORMED_SCAN: 422,
    NO_FACE: 422,
    MULTI_FACE: 422,
    LOW_QUALITY: 422,
    LIVENESS_FAIL: 422,
    CHALLENGE_FAIL: 422,
    USER_NOT_FOUND: 404,
    MODEL_UNAVAILABLE: 503,
    BUSY: 503,
}
